#!/usr/bin/env python3
"""Regenerate config/gp-symbols.txt: every symbol defined in a splat sdata/sbss
data segment. maspsx reads it (--gp-symbols) to emit gp-relative loads and
stores for exactly those symbols, which is how retail reaches them.

    python3 tools/gpsyms.py            # rewrite config/gp-symbols.txt
    python3 tools/gpsyms.py --check    # exit 1 if the committed file is stale

Derived from asm/data/*.sdata.s and *.sbss.s, so run `make extract` first.
"""
import glob, re, sys
LABEL = re.compile(r'^(?:dlabel|glabel)\s+(\S+)')
OUT = 'config/gp-symbols.txt'

def derive():
    syms = set()
    for f in glob.glob('asm/data/*.sdata.s') + glob.glob('asm/data/*.sbss.s'):
        for line in open(f):
            m = LABEL.match(line)
            if m:
                syms.add(m.group(1))
    return sorted(syms)

def main():
    syms = derive()
    if not syms:
        sys.exit('no sdata/sbss labels found under asm/data/ -- run make extract')
    body = ('# GENERATED by tools/gpsyms.py -- symbols defined in the sdata/sbss\n'
            '# segments of config/splat.slps01556.lsdde.yaml. maspsx --gp-symbols\n'
            '# addresses these off $gp. Regenerate after any sdata/sbss carve.\n'
            + '\n'.join(syms) + '\n')
    if '--check' in sys.argv:
        try:
            cur = open(OUT).read()
        except FileNotFoundError:
            cur = ''
        if cur != body:
            sys.exit(f'{OUT} is stale -- run python3 tools/gpsyms.py')
        print(f'OK: {OUT} current ({len(syms)} symbols)')
        return
    try:
        cur = open(OUT).read()
    except FileNotFoundError:
        cur = ''
    if cur != body:   # untouched when current: every object depends on its mtime
        open(OUT, 'w').write(body)
        print(f'wrote {OUT}: {len(syms)} symbols')
    else:
        print(f'{OUT} current ({len(syms)} symbols)')
    # every gp_rel target retail uses must be in the list
    targets = set()
    for f in glob.glob('asm/**/*.s', recursive=True):
        for m in re.finditer(r'%gp_rel\(([A-Za-z_0-9]+)', open(f).read()):
            targets.add(m.group(1))
    missing = sorted(targets - set(syms))
    if missing:
        print(f'WARNING: {len(missing)} retail %gp_rel targets not in list: {missing[:8]}')

if __name__ == '__main__':
    main()
