#!/usr/bin/env bash
# Provision a decomp-permuter directory for one function.
#
#   tools/setup-permuter.sh <func> <seed.c> [outdir]
#
# <seed.c> is a small C file holding the project #includes plus ONE function
# definition -- the near-miss body, normally copied out of that function's
# match report. <outdir> defaults to permuter-work/<func> (gitignored).
#
# Then:
#   PATH=$PWD/permuter-work/bin:$PATH \
#     .venv/bin/python3 tools/decomp-permuter/permuter.py \
#       -j 6 --stop-on-zero --best-only permuter-work/<func>
#
# WHY THIS SCRIPT EXISTS. Setting this up by hand hits four traps that each
# look like a broken toolchain, and all four cost real time the first time
# (round 8, 2026-09-02). They are fixed here so nobody pays twice:
#
#   1. `prelude.inc` ends with `.set gp=64`, and our `as` rejects that against
#      an r3000: "`gp=64' used with a 32-bit processor". Dropped below.
#   2. The permuter's scorer shells out to `mips-linux-gnu-objdump`, hardcoded.
#      Ours is `mipsel-linux-gnu-objdump`. A PATH shim directory of symlinks
#      fixes it WITHOUT touching the vendored permuter or the build -- see
#      permuter-work/bin, created here.
#   3. maspsx emits `.include "include/labels.inc"`, a REPO-RELATIVE path, but
#      the permuter runs compile.sh from its own directory. compile.sh
#      therefore passes `-I$REPO` as well as `-I$REPO/include`.
#   4. `strip_other_fns.py` prunes typedefs it thinks are unused. The permuter
#      itself copes, but a hand-rolled scoring harness built on the stripped
#      base.c will die with "parse error before `*'" on the target's own
#      return type. Score candidates against the REAL headers instead.
#
# THE COMPILE PIPELINE HERE IS THE MAKEFILE'S, VERBATIM. The permuter mutates
# SOURCE under a fixed toolchain -- that is why using it is not a toolchain
# change, and it stops being true the moment these flags drift from
# Makefile:113. If you change one, you are no longer permuting this project.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO=$(pwd)

func=${1:?usage: setup-permuter.sh <func> <seed.c> [outdir]}
seed=${2:?usage: setup-permuter.sh <func> <seed.c> [outdir]}
dir=${3:-permuter-work/$func}

[ -f "$seed" ] || { echo "FATAL: no such seed file: $seed" >&2; exit 1; }

# Find the function's disassembly without being told which unit it is in.
asm=$(find asm/nonmatchings -name "$func.s" -print -quit)
[ -n "$asm" ] || { echo "FATAL: no asm/nonmatchings/**/$func.s -- is it already matched?" >&2; exit 1; }
echo "target asm: $asm"

mkdir -p "$dir" permuter-work/bin

# Trap 2: the scorer's hardcoded tool names.
for t in objdump as; do
    ln -sf "$REPO/tools/binutils/bin/mipsel-linux-gnu-$t" "permuter-work/bin/mips-linux-gnu-$t"
done

# --- compile.sh: Makefile:113, with trap 3's extra -I ------------------------
cat > "$dir/compile.sh" <<SH
#!/bin/bash
# GENERATED by tools/setup-permuter.sh -- the Makefile's C rule, verbatim.
set -euo pipefail
REPO=$REPO
CPP_FLAGS="-I\$REPO/include -I\$REPO/include/psyq -undef -Wall -lang-c -nostdinc
 -Dmips -D__GNUC__=2 -D__OPTIMIZE__ -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx
 -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D_LANGUAGE_C -DLANGUAGE_C"
CC_FLAGS="-mips1 -mcpu=3000 -quiet -Wall -fno-builtin -mno-abicalls
 -funsigned-char -G0 -O2"
MASPSX_FLAGS="--aspsx-version=2.34 --dont-force-G0 --expand-div"
# -I\$REPO is trap 3: maspsx emits a repo-relative .include "include/labels.inc"
AS_FLAGS="-I\$REPO -I\$REPO/include -I\$REPO/include/psyq -march=r3000
 -mtune=r3000 -EL -no-pad-sections -G0 -O2"
INPUT=\$1; shift
\$REPO/tools/gcc263/cpp \$CPP_FLAGS "\$INPUT" \\
  | \$REPO/tools/gcc263/cc1 \$CC_FLAGS \\
  | \$REPO/.venv/bin/python3 \$REPO/tools/maspsx/maspsx.py \$MASPSX_FLAGS \\
  | \$REPO/tools/binutils/bin/mipsel-linux-gnu-as \$AS_FLAGS "\$@"
SH
chmod +x "$dir/compile.sh"

printf 'func_name = "%s"\ncompiler_type = "gcc"\n' "$func" > "$dir/settings.toml"

# --- target.o: retail's own bytes -------------------------------------------
# Trap 1: drop `.set gp=64`. Drop splat's leading .set/nonmatching lines too --
# the prelude already supplies them, and `nonmatching` would be invoked before
# its own macro definition.
grep -v '^\.set gp=64' tools/decomp-permuter/prelude.inc > "$dir/target.s"
sed -e '1,4d' "$asm" >> "$dir/target.s"
tools/binutils/bin/mipsel-linux-gnu-as -march=r3000 -mtune=r3000 -EL \
    -no-pad-sections -G0 -O2 "$dir/target.s" -o "$dir/target.o"

# --- base.c: the seed, preprocessed and reduced to one function -------------
cp "$seed" "$dir/orig.c"
tools/gcc263/cpp -Iinclude -Iinclude/psyq -undef -lang-c -nostdinc \
  -Dmips -D__GNUC__=2 -D__OPTIMIZE__ -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx \
  -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D_LANGUAGE_C -DLANGUAGE_C \
  -D'__attribute__(x)=' "$dir/orig.c" | grep -v '^#' > "$dir/base.c"
.venv/bin/python3 tools/decomp-permuter/strip_other_fns.py "$dir/base.c" "$func"

# --- prove the scaffold before handing it over ------------------------------
# A permuter dir whose base does not even compile wastes a whole search, and
# one whose base score is not the score the match report claims is scoring
# something other than the function you think it is.
"$dir/compile.sh" "$dir/base.c" -o "$dir/base.o"
echo
echo "scaffold built in $dir -- base compiles, target assembled."
echo "Sanity-check the base score against the match report BEFORE searching:"
echo
echo "  PATH=$REPO/permuter-work/bin:\$PATH \\"
echo "    .venv/bin/python3 tools/decomp-permuter/permuter.py --debug $dir"
echo
echo "Then search (a zero is a LEAD -- translate it to idiomatic C and"
echo "re-verify with ./build-and-verify.sh plus tools/funcdiff.py):"
echo
echo "  PATH=$REPO/permuter-work/bin:\$PATH \\"
echo "    .venv/bin/python3 tools/decomp-permuter/permuter.py -j 6 \\"
echo "      --stop-on-zero --best-only $dir"
